spring.application.name=FarmVerse
server.port=8085

# Database Configuration
spring.datasource.url=YOUR_DATABASE_URL
spring.datasource.username=YOUR_DATABASE_USERNAME
spring.datasource.password=YOUR_DATABASE_PASSWORD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hikari Connection Pool
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.transaction-isolation=TRANSACTION_READ_COMMITTED

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
app.jwt.secret=YOUR_JWT_SECRET
app.jwt.expiration-ms=86400000

# FarmVerse AI - Groq
groq.api.key=YOUR_GROQ_API_KEY
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.model=openai/gpt-oss-120b

# Real-time Weather API
weatherapi.api.key=YOUR_WEATHERAPI_API_KEY
weatherapi.forecast.url=https://api.weatherapi.com/v1/forecast.json

# Mandi Market Prices - Government of India data.gov.in
mandi.api.key=YOUR_MANDI_API_KEY
mandi.api.url=https://api.data.gov.in/resource/9ef84268-d588-465a-a308-a864a43d0070